CocktailDB WebApp/Controllers/ListByIngredientController.cs
using CocktailDB_WebApp.Models;
using CocktailDB_WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CocktailDB_WebApp.Controllers
{
    public class ListByIngredientController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Search(string searchText)
        {
            if (!string.IsNullOrEmpty(searchText))
            {
                ViewBag.results = searchText;
                ListByIngredientModel.Root drinks = new ListByIngredientModel.Root();
                drinks = await ApiService.GetListByIngredient(searchText);
                if (drinks.drinks != null)
                {
                    return View(drinks);
                }
                else
                {
                    return RedirectToAction("Index", "Error");
                }

            }
            else
            {
                return RedirectToAction("Index", "Error");
            }

        }
    }
}

CocktailDB WebApp/Controllers/NonAlcoholicDrinkController.cs
using CocktailDB_WebApp.Models;
using CocktailDB_WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CocktailDB_WebApp.Controllers
{
    public class NonAlcoholicDrinkController : Controller
    {
        public async Task<IActionResult> Index()
        {
            NonAlcoholicDrinkModel.Root drinks = new NonAlcoholicDrinkModel.Root();
            drinks = await ApiService.GetNonAlcoholicDrinks();

            return View(drinks);
        }
    }
}

CocktailDB WebApp/Controllers/RandomDrinkController.cs
using CocktailDB_WebApp.Models;
using CocktailDB_WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CocktailDB_WebApp.Controllers
{
    public class RandomDrinkController : Controller
    {
        public async Task<IActionResult> Index()
        {
            DrinkModel.Drink drink = new DrinkModel.Drink();
            DrinkModel.Root drinks = new DrinkModel.Root();
            drinks = await ApiService.GetARandomDrink();

            foreach (var drinkToUse in drinks.drinks)
            {
                drink = drinkToUse;
            }

            return View(drink);
        }
    }
}

CocktailDB WebApp/Controllers/SearchByLetterController.cs
using CocktailDB_WebApp.Models;
using CocktailDB_WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CocktailDB_WebApp.Controllers
{
    public class SearchByLetterController : Controller
    {
        public async Task<IActionResult> Index(string letter)
        {
            SearchByLetterModel.Root drinks = new SearchByLetterModel.Root();
            drinks = await ApiService.GetDrinksByLetter(letter);

            return View(drinks);
        }
    }
}

CocktailDB WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CocktailDB_WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CocktailDB_WebApp.styles.css" asp-append-version="true" />
</head>
@*<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CocktailDB_WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>*@
<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
    </header>
    <nav>
        <ul>
            <li class="logo"><img src="/image/vinicius-amnx-amano-V1zGiNVPumM-unsplash.jpg"></li>
            <li><a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
            <li><a class="nav-link text-light" href="@Url.Action("Index", "SearchByLetter", new{letter = "a"})">Drinks</a></li>
            <li><a class="nav-link text-light" href="@Url.Action("Index", "NonAlcoholicDrink")">Clean Drinks</a></li>
            <li><a class="nav-link text-light" href="@Url.Action("Index", "ListByIngredient")">Search with an ingredient</a></li>
            <li><a class="nav-link text-light" href="@Url.Action("Index", "RandomDrink")">Random Drink!</a></li>

            @*  <li><a href="#"><i class="fa fa-book"></i>&nbsp;  Drinks</a></li>*@
        </ul>
    </nav>

    <div id="content" class="container p-3">
        <div id="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
     
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Jamey Geoghagan
            &copy; <p>JGG</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>