CocktailDB WebApp/Controllers/HomeController.cs
using CocktailDB_WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CocktailDB_WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CocktailDB WebApp/Controllers/ListByIngredientController.cs
using CocktailDB_WebApp.Models;
using CocktailDB_WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CocktailDB_WebApp.Controllers
{
    public class ListByIngredientController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Search(string searchText)
        {
            if (!string.IsNullOrEmpty(searchText))
            {
                ViewBag.results = searchText;
                ListByIngredientModel.Root drinks = new ListByIngredientModel.Root();
                drinks = await ApiService.GetListByIngredient(searchText);
                if (drinks.drinks != null)
                {
                    return View(drinks);
                }
                else
                {
                    return RedirectToAction("Index", "Error");
                }

            }
            else
            {
                return RedirectToAction("Index", "Error");
            }

        }
    }
}

CocktailDB WebApp/Controllers/RandomDrinkController.cs
using CocktailDB_WebApp.Models;
using CocktailDB_WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CocktailDB_WebApp.Controllers
{
    public class RandomDrinkController : Controller
    {
        public async Task<IActionResult> Index()
        {
            DrinkModel.Drink drink = new DrinkModel.Drink();
            DrinkModel.Root drinks = new DrinkModel.Root();
            drinks = await ApiService.GetARandomDrink();

            foreach (var drinkToUse in drinks.drinks)
            {
                drink = drinkToUse;
            }

            return View(drink);
        }
    }
}

CocktailDB WebApp/Controllers/SearchByLetterController.cs
using CocktailDB_WebApp.Models;
using CocktailDB_WebApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CocktailDB_WebApp.Controllers
{
    public class SearchByLetterController : Controller
    {
        public async Task<IActionResult> Index(string letter)
        {
            SearchByLetterModel.Root drinks = new SearchByLetterModel.Root();
            drinks = await ApiService.GetDrinksByLetter(letter);

            return View(drinks);
        }
    }
}

CocktailDB WebApp/Controllers/SearchByNameController.cs
using CocktailDB_WebApp.Models;
using CocktailDB_WebApp.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.ObjectModel;

namespace CocktailDB_WebApp.Controllers
{
    public class SearchByNameController : Controller
    {
        public async Task<IActionResult> Index(string searchText)
        {
            if (!string.IsNullOrEmpty(searchText))
            {
                ViewBag.results = searchText;
                SearchByNameModel.Root drinksByName = new SearchByNameModel.Root();

                drinksByName = await ApiService.SearchByName(searchText);
                if (drinksByName.drinks != null)
                {
                    return View(drinksByName);
                }
                else
                {
                    return RedirectToAction("Index", "Error");
                }

            }
            else
            {
                return RedirectToAction("Index", "Error");
            }

        }

        public async Task<IActionResult> DrinkByID(int id)
        {
            DrinkModel.Drink theDrink = new DrinkModel.Drink();
            DrinkModel.Root drinks = new DrinkModel.Root();
            drinks = await ApiService.GetDrinkByID(id);
            foreach (var drink in drinks.drinks)
            {

                theDrink = drink;
            }

            return View(theDrink);
        }
    }
}

CocktailDB WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class='centerAlign'>
    <div style="background-image: url(Image/header.jpg)" class="jumbotron bg-cover text-white align-content-lg-around">
        <div class="container py-5 text-center">
            <h1 class="display-4 font-weight-bold">Welcome to the cocktail database</h1>
            <p class="font-italic mb-0">This is just a fun project that will help you find a drink to try!</p>
            <p class="font-italic">
                App made by Jamey Geoghagan check out my git hub
            </p>
            <a href="https://github.com/JameyGeoghagan" role="button" class="btn-light btn-primary px-5">GitHub</a>
        </div>
    </div>
    <div class="container">
        <br />
        <div class="row justify-content-center">
            <div class="col-12 col-md-10 col-lg-8">
                <form asp-controller="SearchByName" asp-action="Index" class="card card-sm">
                    <div class="card-body row no-gutters align-items-center">
                        <div class="col-auto">
                            <i class="fas fa-search h4 text-body"></i>
                        </div>
                        <!--end of col-->
                        <div class="col">
                            <input class="form-control form-control-lg form-control-borderless" name="searchText" type="search" placeholder="Search for a drink!">
                        </div>
                        <!--end of col-->
                        <div class="col-auto">
                            <button class="btn-light btn-lg btn-success" type="submit" value="searchText">Search</button>
                        </div>
                        <!--end of col-->
                    </div>
                </form>
            </div>
            <!--end of col-->
        </div>
    </div>

    <div class="container mx-auto mt-4">
        <div class="row centerAlign">
            @*    <div class="col-md-4">
            <div class="card" style="width: 18rem;">
            <img src="https://i.imgur.com/ZTkt4I5.jpg" class="card-img-top" alt="...">
            <div class="card-body">
            <h5 class="card-title">Popular Drinks</h5>
            <p class="card-text">This will bring you some of the most popular drinks and how to make them!</p>
            <a href="#" class="btn "><i class="fab fa-github"></i> Check it out</a>
            </div>
            </div>
            </div>*@
            <div class="col-md-5">
                <div class="card" style="width: 18rem;">
                    <img src="/image/listByLetterCard.jpg" class="card-img-top img-fluid" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">List of all our Drinks!</h5>
                        <p class="card-text">Here you will be able to search through the drinks</p>
                        <a href="@Url.Action("Index", "SearchByLetter", new{letter = "a"})" class="btn-light"><i class="fab fa-github"></i> Check it out</a>
                    </div>
                </div>
            </div>

            <div class="col-md-5">
                <div class="card" style="width: 18rem;">
                    <img src="/image/nonAlcoholicCard.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Check out the non alcoholic drinks</h5>
                        <p class="card-text">Drinks for the wonderfull DD, or just fun drinks to make that do not have alcohol in them</p>
                        <a href="@Url.Action("Index", "NonAlcoholicDrink")" class="btn-light"><i class="fab fa-github"></i> Check it out</a>
                    </div>
                </div>
            </div>
            <div class="col-md-5 align-content-lg-center">
                <div class="card" style="width: 18rem;">
                    <img src="~/image/randomDrinkCard.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Try the random drink generator</h5>
                        <p class="card-text">If you just dont know what to check out, try the radom drink. It pulls a drink for you to try!</p>
                        <a href="@Url.Action("Index", "RandomDrink")" class="btn-light"><i class="fab fa-github"></i> Check it out</a>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card" style="width: 18rem; ">
                    <img src="/image/drinkIngredient.jpg" class="card-img-top img-fluid" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Search by ingredient</h5>
                        <p class="card-text">Have a ingresient in mind well search the drinks based on the ingredient you provid</p>
                        <a href="@Url.Action("Index", "ListByIngredient")" class="btn-light "><i class="fab fa-github"></i> Check it out</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>